apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer-app
  labels:
    app: iot-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-demo
        name: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: danistrebel/strimzi-consumer-app:latest
          env:
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: viscon-cluster-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: iot-consumer
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: iot-consumer
                  key: user.key
            - name: BOOTSTRAP_SERVERS
              value: "viscon-cluster-kafka-bootstrap:9093"
            - name: CONSUMER_GROUP_ID
              value: "iot-consumers"
            - name: CONSUMER_TOPIC
              value: "iot-temperature-max"
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-demo
    name: consumer-app
  name: consumer-app
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: consumer-app
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: iot-demo
    name: consumer-app
  name: consumer-app
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: consumer-app
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
