apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: iot-consumer
  labels:
    app: iot-demo
    strimzi.io/cluster: viscon-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: iot-temperature-max
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: iot-temperature-max
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: iot-consumers
          patternType: prefix
        operation: Read
        host: "*"
