apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-app
  labels:
    app: iot-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot-demo
        name: device-app
    spec:
      containers:
        - name: device-app
          image: danistrebel/strimzi-device-app:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: "viscon-cluster-kafka-bootstrap:9093"
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: viscon-cluster-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: iot-device
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: iot-device
                  key: user.key
            - name: TOPIC_TEMPERATURE
              value: "iot-temperature"
            - name: DELAY
              value: "1000"
            - name: MIN_TEMPERATURE
              value: "15"
            - name: MAX_TEMPERATURE
              value: "25"
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
