apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: iot-temperature
  labels:
    app: iot-demo
    strimzi.io/cluster: viscon-cluster
spec:
  partitions: 4
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: iot-temperature-max
  labels:
    app: iot-demo
    strimzi.io/cluster: viscon-cluster
spec:
  partitions: 4
  replicas: 2
