apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: consumer-0
  labels:
    strimzi.io/cluster: viscon-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: viscon-auth
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: viscon-auth
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: consumer-group
          patternType: literal
        operation: Read
        host: "*"
